server:
  port: 9001

spring:
  application:
    name: MPESA-SERVICE

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mariadb://localhost:3306/connect
    username: root
    password: sudoFortune
    driverClassName: org.mariadb.jdbc.Driver

eureka:
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost

mpesa:
  app:
    consumer:
      key: onUXiqfDTmWFagIZYyFu5LAiXva6JCv1
      secret: UUUlFYplL4c5sKUX
  b2c:
    validationUrl: payup.fortunecredit.co.ke/mobile/validate/payment
    confirmationUrl: payup.fortunecredit.co.ke/mobile/confirm/payment
  initiator:
    name:

fortunecredit:
  url:
    sit: https://api.sit.fortunecredit.co.ke/
    production: https://api.fortuneconnect.fortunecredit.co.ke/
    connect: https://api.connect.fortunecredit.co.ke/

integration:
  mpesa:
    username: MPESA
    password: mpesa@FortuneIntegration22

  daraja:
    username: DARAJA
    password: mpesa@FortuneIntegration22